version: '3.8'
services:
  app-server:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: leadsystem-app-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://107.21.182.152/sys?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TestPassword12!
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend


  app-client:
    image: leadsystem-app-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  mysqldb:
    container_name: mysqldb
    image: leadsystem-app-db
    build:
      context: db_init
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: sys
      MYSQL_PASSWORD: TestPassword12!
      MYSQL_ROOT_PASSWORD: TestPassword12!
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    networks:
      - backend
volumes:
  db_init:


# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: